Feature/signin
GDSC-Daejin/gdsc-dju-blog-fe pull request #30
Opened 2022-03-22 07:02 UTC by bjc1102

## 작업 내용 (Content)

## 기타 사항 (Etc)

## Merge 전 필요 작업 (Checklist before merge)
- [x] component 대소문자 확인
- [x] conflict 해결
- [ ] develop branch로 merge하나요?

## Merge 후 필요 작업 (Checklist after merge)
- PR이 생성되면 코드 리뷰 요청한 개발자에게 슬랙으로 알려주세요.

2022-05-28 08:10 UTC, HyeokE requested changes

2022-05-28 08:10 UTC, HyeokE commented on src/pages/OauthRedirectPage/index.tsx
> +    (async function () {
useGetUserData파일에 async 선언된 함수 하나 더 있을텐데 그거 export 해서 쓰시면 더 이쁠 것같아요

```
const getUserData = async (token: string) => {
  const response = await API.getUserData();
  return response.data.body.data;
};
```

useEffect에 함수 다 넣지 말고 userTokenCookieHandler 하나 선언해서 기능 합친 후에 useEffect에 넣으시는게 더 좋아보여요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SearchResult/index.tsx
> +  const getSearchList = async () => {
이 부분 api/index.ts에 넣어주세요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SearchResult/index.tsx
> +      return response.data.body.data.content
이것도 반복되는 부분 변수 선언으로 해주시면 좋을 것같아요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SearchResult/styled.tsx
> +  h2 {
폰트 사이즈 asset 사용해주세요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SearchResult/index.tsx
> +        {postData?.length ? (
postData 받는 스키마에 데이터 유무 체크하는 key하나 있을텐데 그걸로 검증해주세요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SearchResult/styled.tsx
> +    font-size: 1.5rem;
`${({theme}) => theme.fontSize.body2}`이런식으로 변경해주세요 만약 폰트사이드 지정 안되어있으면 디자이너 호출하셔야할 것같아요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SignUp/SignUpForm/FormStructureInfo.ts
> +export interface IFormStructure {
type 폴더에 signUpFormType.d.ts 선언해서 가져와주세요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SignUp/SignUpInput/styled.tsx
> +  font-size: 16px;
폰트사이즈 에셋 적용해주세요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SignUp/SignUpInput/styled.tsx
> +    font-size: 12px;
폰트사이즈 에셋 적용해주세요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SignUp/SignUpSelect/styled.tsx
> +  background-color: #fff;
white도 에셋으로 지정되어있습니다

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SignUp/SignUpSelect/styled.tsx
> +  background-color: #fff;
에셋 적용해주세요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SignUp/SignUpSelect/styled.tsx
> +  /* height: 48px; 288px; */
주석 제거해주세요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SignUp/SignUpSelect/styled.tsx
> +  font-size: 16px;
에셋 적용해주세요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SignUp/SignUpSelect/styled.tsx
> +export const SignUpColorCircle = styled.div<{ color: string }>`
color type을 `<{color: keyof typeof theme.colors}>`로 하시면 `handleColorType`을 하실 필요가 없습니당

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SignUp/styled.tsx
> +  font-size: 18px;
에셋 적용해주세요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SignUp/styled.tsx
> +    font-size: 12px;
에셋 적용해주세요

2022-05-28 08:10 UTC, HyeokE commented on src/pages/SignUp/styled.tsx
> +  font-size: 14px;
에셋 적용해주세요

2022-05-29 12:01 UTC, bjc1102 commented on src/pages/SignUp/SignUpSelect/styled.tsx
> +export const SignUpColorCircle = styled.div<{ color: string }>`
변수명을 잘못 설정해서 바꿨습니다

2022-06-20 12:25 UTC, HyeokE approved these changes

2022-06-20 12:25 UTC, merged